from tkinter import*
root=Tk()
h,w=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry('%dx%d+0+0'%(h,w))

frame1=Frame(root)
frame1.grid(row=0,column=2,padx=50)
bus=PhotoImage(file='.\\bus.png')
Label(frame1,image=bus).grid(row=0,column=0,columnspan=10,padx=w//3)
Label(frame1,text="Online Bus Booking System",bg='light blue',fg='red',font='Arial 24 bold').grid(row=2,column=2,columnspan=10,pady=20)
Button(frame1,text='Enter Journey Details',bg='light green',font='Arial 16 bold').grid(row=4,column=5)
Label(frame1,text="To",font='Arial 12 bold').grid(row=6,column=1,sticky=E)
Entry(frame1).grid(row=6,column=2,pady=20)
Label(frame1,text="From",font='Arial 12 bold').grid(row=6,column=3,sticky=E)
Entry(frame1).grid(row=6,column=4,pady=30)
Label(frame1,text="Journey Date",font='Arial 12 bold').grid(row=6,column=5,sticky=E)
Entry(frame1).grid(row=6,column=6,pady=40)
Button(frame1,text='Show Bus',bg='darkgreen',font='Arial 14 bold').grid(row=6,column=7,sticky=E)

    
home=PhotoImage(file='.\\home.png')
Label(frame1,image=home).grid(row=6,column=8)

Label(frame1,text="Fill the Passenger Details to Book the Ticket",bg='light blue',fg='red',font='Arial 20 bold').grid(row=7,column=2,columnspan=10,pady=20)
Label(frame1,text="Name",font='Arial 12 bold').grid(row=8,column=0,sticky=E)
Entry(frame1).grid(row=8,column=1,pady=30)
Label(frame1,text='Gender',font='Arial 12').grid(row=8,column=2)
Gender=StringVar()
option=["MALE","FEMALE","OTHER"]
menu=OptionMenu(frame1,Gender,*option).grid(row=8,column=3)
Label(frame1,text="No. of seats",font='Arial 12 bold').grid(row=8,column=4,sticky=E)
Entry(frame1).grid(row=8,column=5,pady=30)
Label(frame1,text="Mobile No:",font='Arial 12 bold').grid(row=8,column=6,sticky=E)
Entry(frame1).grid(row=8,column=7,pady=30)
Label(frame1,text="Age",font='Arial 12 bold').grid(row=8,column=8,sticky=E)
Entry(frame1).grid(row=8,column=9,pady=30)
Button(frame1,text='Book Seat',bg='darkgreen',font='Arial 14 bold').grid(row=8,column=10,sticky=E)
root.mainloop()
