from tkinter import*
root=Tk()
h,w=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry('%dx%d+0+0'%(h,w))
bus=PhotoImage(file='.\\bus.png')
Label(root,image=bus).grid(row=0,column=0,columnspan=15,padx=w//2.5)
Label(root,text="Online Bus Booking System",bg='light blue',fg='red',font='Arial 24 bold').grid(row=1,column=0,columnspan=15,padx=w//2.5,pady=h//30)
Label(root,text="Add Bus Route Details",bg='white',fg='green',font='Arial 18 bold').grid(row=2,column=0,columnspan=15,padx=h//2.5,pady=h//30)
Label(root,text="Route id",font='Arial 12 bold').grid(row=3,column=0)
Entry(root).grid(row=3,column=1)
Label(root,text="Station Name",font='Arial 12 bold').grid(row=3,column=2)
Entry(root).grid(row=3,column=3)
Label(root,text="Station  id",font='Arial 12 bold').grid(row=3,column=4)
Entry(root).grid(row=3,column=5)
Button(root,text="Add Route ",bg='green',font='Arial 14 bold').grid(row=3,column=8,pady=w//20)
Button(root,text="Delete Route",bg='green',font='Arial 14 bold').grid(row=3,column=9)
home=PhotoImage(file='.\\home.png')
Label(root,image=home).grid(row=4,column=8)
root.mainloop()
