from tkinter import*
root=Tk()
h,w=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry('%dx%d+0+0'%(h,w))
bus=PhotoImage(file='.\\bus.png')
Label(root,image=bus).grid(row=0,column=0,columnspan=15,padx=w//2.5)
Label(root,text="Online Bus Booking System",bg='light blue',fg='red',font='Arial 24 bold').grid(row=1,column=0,columnspan=15,padx=w//2.5,pady=h//30)
Label(root,text="Add Bus Details",bg='white',fg='green',font='Arial 18 bold').grid(row=2,column=0,columnspan=15,padx=h//2.5,pady=h//30)
Label(root,text="Bus id",font='Arial 12 bold').grid(row=3,column=0)
Entry(root).grid(row=3,column=1)
Label(root,text="Capacity",font='Arial 12 bold').grid(row=3,column=2)
Entry(root).grid(row=3,column=3)
Label(root,text="Fare Rs",font='Arial 12 bold').grid(row=3,column=4)
Entry(root).grid(row=3,column=5)
Label(root,text="Operator id",font='Arial 12 bold').grid(row=3,column=6)
Entry(root).grid(row=3,column=7)
Label(root,text="Route id",font='Arial 12 bold').grid(row=3,column=8)
Entry(root).grid(row=3,column=9)
Button(root,text="Add Bus ",bg='green',font='Arial 14 bold').grid(row=4,column=5,pady=w//20)
Button(root,text="Edit Bus",bg='green',font='Arial 14 bold').grid(row=4,column=6)
home=PhotoImage(file='.\\home.png')
Label(root,image=home).grid(row=4,column=7)
Label(root,text='Bus type',font='Arial 12').grid(row=3,column=10)
bus_type=StringVar()
option=['AC 2*2','AC 3*2','NON-AC 2*2','AC SLEEPER']
menu=OptionMenu(root,bus_type,*option).grid(row=3,column=11)
root.mainloop()
